# Generated by Django 5.1 on 2024-09-11 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_customuser_cpf_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cpf', regex='^\\d{11}$')]),
        ),
    ]
