# Generated by Django 5.1 on 2024-09-07 20:10

import django.db.models.deletion
import embed_video.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=260)),
                ('duration', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('url', embed_video.fields.EmbedVideoField()),
                ('thumbnail', models.FileField(upload_to='uploads/thumbnails')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('classification', models.CharField(max_length=5)),
                ('type', models.CharField(default='movie', max_length=10)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('thumbnail', models.FileField(upload_to='uploads/thumbnails')),
                ('classification', models.CharField(blank=True, max_length=5, null=True)),
                ('seasons', models.PositiveIntegerField()),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(default='serie', max_length=10)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('season', models.PositiveIntegerField()),
                ('episode_number', models.PositiveIntegerField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('url', embed_video.fields.EmbedVideoField()),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='content.serie')),
            ],
        ),
    ]
